name: ci - lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]

jobs:
  json:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-json.yml@main

  yaml:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-yaml.yml@main

  markdown:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-md.yml@main

  conventional-commits:
    if: github.event_name == 'pull_request'
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-commits-conventional.yml@main
    permissions:
      pull-requests: read
